### ISSUE TITLE
get function returns JsonValue that needs to be re-cast every time

### ISSUE THREAD

**Issue by berkbuzcu** [azu/kvs#29]
Hello again!

Here with a suggestion this time.

This is normally non issue but I couldn't find out a way to go with the set(customKey, list) signatures and I have to manually convert JSON to list every time. Maybe implementing .toList or .toDict sort of functions could be a good idea!

**Comment by azu** [comment]
What type is the `list`?

KVS treat the value as JSON value.
It means that KVS apply `JSON.stringify`/`JSON.parse` to saving/loading value.

```js
(async () => {
    const { kvsIndexedDB } = await import("https://unpkg.com/@kvs/indexeddb@2.1.1?module");
    const storage = await kvsIndexedDB({
        name: "database-name",
        version: 1
    });
    const list = [1, 2, 3];
    await storage.set("list", list);
    const savedList = await storage.get("list");
    console.log(savedList); // [ 1, 2, 3 ]
})();
```

📝 JSON-able value is `string | number | boolean | null | JsonObject | JsonArray;`
KVS can not serialize Map or Set automatically.

- [JSON.stringify() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)
- [JSON.stringify() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

**Comment by berkbuzcu** [comment]
Hello, 

Thanks for the quick reply!

![resim](https://user-images.githubusercontent.com/6241929/156580704-b47e2617-1fa0-48bf-a69e-d1892a071649.png)

![resim](https://user-images.githubusercontent.com/6241929/156580926-927fdb32-0b54-4522-b74e-5774bca9a21f.png)

The signature was misleading me and my error was elsewhere, I solved it by the time you replied but what I meant was simply casting it to string[]

I just realized the error is elsewhere and "as string[]" works perfectly.

This can be closed whenever you feel satisfied!

Best regards

**Comment by azu** [comment]
KVS support StorageSchema type as generics.
https://github.com/azu/kvs#typescript

```ts
type StorageSchema = {
    // key is string
    // value is string[]
    [index:string]: string[]
};
const storage = await kvsIndexedDB<StorageSchema>({
    name: databaseName,
    version: 1
});
await storage.set("a1", ["string"]); 
const a1 = await storage.get("a1");
````
<img width="590" alt="image" src="https://user-images.githubusercontent.com/19714/156584595-c4f14f55-c158-49cc-a388-cbd16ef3e9b6.png">

I do not understand all, but if you provice reproduce code, I can investigate it.
Feel free to reopen if kvs's type is wrong.

- https://github.com/azu/kvs/blob/master/packages/types/src/index.ts
