### ISSUE TITLE
Version stays at 1

### ISSUE THREAD

**Issue by Kalabasa** [azu/kvs#30]
Version is always 1, no matter what you put in. It also causes the `upgrade` function to be called every time.

```ts
kvsEnvStorage({
  name: 'data',
  version: 2,
  upgrade: (_, old, new) => console.log('I am always called', old, new), // I am always called 1 2
})
```

**Comment by azu** [comment]
Can you provide reproduce example?

browser:

```js
(async () => {
  const { kvsEnvStorage } = await import("https://cdn.skypack.dev/@kvs/env@2.1.2");
  const storage = await kvsEnvStorage({
    name: "database-name",
    version: 2,
    async upgrade({ kvs, oldVersion, newVersion }) {
      console.log({
        oldVersion, // 0
        newVersion // 2
      });
    }
  });
})();
```

node:

https://replit.com/@azu2/kvs-env-new-version?v=1#index.js

**Comment by Kalabasa** [comment]
It is reproducible it in your node replit example. Check `~/kvs-env-new-version/.cache/kvs-node-localstorage/database-name.__.__kvs_version__`. Version is always `1`, regardless of the version in the app.

**Comment by Kalabasa** [comment]
Another example:
https://replit.com/@Kalabasa-/kvs-env-new-version#index.js

**Comment by azu** [comment]
https://github.com/azu/kvs/blob/7b4953ee016bae296d6f8ad5847803de06322823/packages/storage/src/storage.ts#L120-L131
Maybe, we need to write version to storage.

**Comment by azu** [comment]
Fixed in https://github.com/azu/kvs/releases/tag/v2.1.3
