### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "@kvs/env". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [azu/kvs#36]
i am trying to run this simple demo code

```
import { kvsEnvStorage } from "@kvs/env";
const storage = await kvsEnvStorage({
    name: "database-name",
    version: 1
});
await storage.set("a1", "string"); // type check
await storage.set("b2", 42);
await storage.set("c3", false);
const a1 = await storage.get("a1"); // a1 will be string type
const b2 = await storage.get("b2");
const c3 = await storage.get("c3");
```

but i receive this error: 
`Uncaught TypeError: Failed to resolve module specifier "@kvs/env". Relative references must start with either "/", "./", or "../".`

what am doing wrong here??

Note that i am trying to load the script from browser directly not from node.js. Any help @azu

**Comment by azu** [comment]
In what environment is it running?
If you are using Node.js, you need to install `@kvs/env` beforehand.

**Comment by PanagiotisDrakatos** [comment]
@azu it's working like a charm. You are  awesome man!!! thanks a lot :) :)
